language: node_js
node_js:
- node
branches:
  only:
  - master
notifications:
  email:
    on_success: change
    on_failure: change
install: npm install
script:
- npm run ci_test
deploy:
  provider: npm
  on:
    branch: master
  api_key:
    secure: mmGWn7p8TdSOlyQ8IAbpxQjwuYzwuhtv/R7XaytiFCkHmZmMSMj2CvgP6pn9mFQ3Dtb37Qqyge1fP5yteJjDAqEYd/xedMK+ObR2Hsp9axGJwe6zbr2dl5N+e4I30SO4HLHIEUdJ3tw/qmxG3z+3XFg1vMQ/b/xi3Cz30qjHRAzyy4V/VP7qAuh/PGqo2Wf9sQIMoDUAqtoSplQmFaGYlILhsYwvwt4nAPRvXEql1A08BXQ46EbG7A0/hraP478mt+OFm+02BVg6G4bfZD3gMhzhEN5n5eUFqlcqzM9ySG3vWB2CooUPbPtlN7irSps/QmiPXb59eq0drAmvqXkwPPggemqPKswprf884EgEVxewYF5Z7xietXHHnzDMmEk5zvJepQY779JMGlN0d78oCXskp2JsI3uPF2fSsSQB6TNDD9mjkjyYn9FYvLZckHLJ8N723ktzGrH9/AyZQ1G3sQD6YKfV1rpbvlkcDoWTr/R867EBbuSfVdIOtylDYtYvOGyKU0xgvf3zUS3XLPk+idbONy6pbRwPA5AXFNUoiUWIk3IJvU8ac0l56S0km4vDpYxYrShahM/OB9v4fPzG7MfnqO4kyehcNWQUpnruBctB3873M2I8D3OMB6Oq8livqhWeiIBWZLya8ZCCfN7ahRmo/Dntb87qeu+0wXeD2Gk=
