language: node_js
node_js:
- node
branches:
  only:
  - master
notifications:
  email:
    on_success: change
    on_failure: change
install: npm install
script:
- npm run ci_test
after_success: 
- "./afterSuccess.sh"
deploy:
  provider: npm
  authToken:
    secure: jho1mrEbcWE8jVHiK+729TBRzw4zU/KoUOG7i6Rfz/uEMd/Q+7+xrtAXmiBwBTgpeBC9p7D6qEWfA9dD9UaCvfMaAQywI/plc8S1FYpnE8kR5mAiW2Y5FPyGnCLI1G6e2Uc0KCgq0p9bx/mEqeE5EvEimf/gvIfDrnVOZqD5cUesgJt1ZqSM+l27F6K2ZDe2MV381wuQjP1l+ViMVEzBcQ3VoJc5isz4C1NDubdj1CsRNLLj0/fCKKvz+LINw/D9Dy79YA5VDMlTtSnrRcrwhc2pLryjRo6FNEmoD3mQmiRRd/E2lHVQ4xNUb4DYdokI1tiCjyU9TVM+ijlTxNz/j5VIrtbU5hzshLMVAdTW5atWpFE50wZQsvecYmsmdzyK0Iu6waX5Gb8ptL8UwfzSXwQadNp8U9eGZEnIcI++PQNsr7aA6LDt17x7B48oZsjl4F2PTSW23Yf9FFEV9Z4dWiiobrTME8mOk1EF5TJ3sB8H4O5X8sFqXcPdviZIlF0qnQFpyr7STDt/+8DU2zA462TKDlOPIi2yp9be9rD6iAHgP2mF9w5uSlYUXUSoNI5HbqHm7YbtcS/0OD6wM6SLoHql3A8jm6B52PtXA/deL+K+hyJ02pFhQXsHm7fGvfaXTExGpmLjY9e/vAeA4Vjh26JpzHHjYp5u1J+R+hYUXaY=
  on:
    branch: master
