language: node_js
node_js:
  - "node"

branches:
  only:
  - master

notifications:
  email:
    on_success: change
    on_failure: change

install:
  npm install

script:
  - npm run ci_test

after_success:
  ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov && ./node_modules/.bin/codecov

deploy:
  skip_cleanup: true
  provider: script
  script: ./updateDocs.sh